### ISSUE TITLE
Document with OAS

### ISSUE THREAD

**Issue by PepeCoral** [VideoMinerAISS/video-miner#1]

**Comment by miniluz** [comment]
Implemented in commit https://github.com/VideoMinerAISS/video-miner/commit/87a182024ef7f5fe54f8d6ac11e1269cfc083081.

**Comment by miniluz** [comment]
Widened in https://github.com/VideoMinerAISS/video-miner/commit/a50f64631bbcf181c5c77170629c549e5bc85fbc
